package mapping

import (
	"github.com/abisaidfarias/lbtechapi/models"
	"github.com/abisaidfarias/lbtechapi/viewmodels/request"
	"github.com/abisaidfarias/lbtechapi/viewmodels/responses"
)

func DeviceRequestToDevice(device *request.Device) *models.Device {

	return &models.Device{
		Type:                   device.Type,
		Brand:                  device.Brand,
		CommercialModel:        device.CommercialModel,
		TechnicalModel:         device.TechnicalModel,
		DisplayType:            device.DisplayType,
		DisplaySize:            device.DisplaySize,
		DisplayResolution:      device.DisplayResolution,
		PlatformOs:             device.PlatformOs,
		PlatformVersion:        device.PlatformVersion,
		PlatformChipsetBrand:   device.PlatformChipsetBrand,
		PlatformChipsetModel:   device.PlatformChipsetModel,
		PlatformCpu:            device.PlatformCpu,
		MemoryRom:              device.MemoryRom,
		MemoryRam:              device.MemoryRam,
		MemoryExtended:         device.MemoryExtended,
		MemoryCpu:              device.MemoryCpu,
		MemoryType:             device.MemoryType,
		CameraFront:            device.CameraFront,
		CameraBack:             device.CameraBack,
		CommunicationWlan:      device.CommunicationWlan,
		CommunicationGps:       device.CommunicationGps,
		CommunicationNfc:       device.CommunicationNfc,
		CommunicationRadio:     device.CommunicationRadio,
		CommunicationUsb:       device.CommunicationUsb,
		CommunicationBluetooth: device.CommunicationBluetooth,
		BatteryType:            device.BatteryType,
		BatteryCapacity:        device.BatteryCapacity,
		BatteryState:           device.BatteryState,
		SensorFingerprint:      device.SensorFingerprint,
		SensorProximity:        device.SensorProximity,
		SensorAmbientLight:     device.SensorAmbientLight,
		SensorAccelerometer:    device.SensorAccelerometer,
		SensorGyroscope:        device.SensorGyroscope,
		SensorHall:             device.SensorHall,
		BandGsm:                device.BandGsm,
		BandWcdma:              device.BandWcdma,
		BandLte:                device.BandLte,
		Band5g:                 device.Band5g,
		NetworkGsm:             device.NetworkGsm,
		NetworkWcdma:           device.NetworkWcdma,
		NetworkLte:             device.NetworkLte,
		NetworkVolte:           device.NetworkVolte,
		NetworkVowifi:          device.NetworkVowifi,
		NetworkVilte:           device.NetworkVilte,
		Network5g:              device.Network5g,
		ImageUrl:               device.ImageUrl,
	}
}
func DeviceToDeviceResponse(device *models.Device) *responses.Device {

	return &responses.Device{
		ID:                     device.ID,
		Type:                   device.Type,
		Brand:                  device.Brand,
		CommercialModel:        device.CommercialModel,
		TechnicalModel:         device.TechnicalModel,
		DisplayType:            device.DisplayType,
		DisplaySize:            device.DisplaySize,
		DisplayResolution:      device.DisplayResolution,
		PlatformOs:             device.PlatformOs,
		PlatformVersion:        device.PlatformVersion,
		PlatformChipsetBrand:   device.PlatformChipsetBrand,
		PlatformChipsetModel:   device.PlatformChipsetModel,
		PlatformCpu:            device.PlatformCpu,
		MemoryRom:              device.MemoryRom,
		MemoryRam:              device.MemoryRam,
		MemoryExtended:         device.MemoryExtended,
		MemoryCpu:              device.MemoryCpu,
		MemoryType:             device.MemoryType,
		CameraFront:            device.CameraFront,
		CameraBack:             device.CameraBack,
		CommunicationWlan:      device.CommunicationWlan,
		CommunicationGps:       device.CommunicationGps,
		CommunicationNfc:       device.CommunicationNfc,
		CommunicationRadio:     device.CommunicationRadio,
		CommunicationUsb:       device.CommunicationUsb,
		CommunicationBluetooth: device.CommunicationBluetooth,
		BatteryType:            device.BatteryType,
		BatteryCapacity:        device.BatteryCapacity,
		BatteryState:           device.BatteryState,
		SensorFingerprint:      device.SensorFingerprint,
		SensorProximity:        device.SensorProximity,
		SensorAmbientLight:     device.SensorAmbientLight,
		SensorAccelerometer:    device.SensorAccelerometer,
		SensorGyroscope:        device.SensorGyroscope,
		SensorHall:             device.SensorHall,
		BandGsm:                device.BandGsm,
		BandWcdma:              device.BandWcdma,
		BandLte:                device.BandLte,
		Band5g:                 device.Band5g,
		NetworkGsm:             device.NetworkGsm,
		NetworkWcdma:           device.NetworkWcdma,
		NetworkLte:             device.NetworkLte,
		NetworkVolte:           device.NetworkVolte,
		NetworkVowifi:          device.NetworkVowifi,
		NetworkVilte:           device.NetworkVilte,
		Network5g:              device.Network5g,
		ImageUrl:               device.ImageUrl,
	}
}
