package mapping

import (
	"github.com/abisaidfarias/lbtechapi/models"
	"github.com/abisaidfarias/lbtechapi/viewmodels/request"
	"github.com/abisaidfarias/lbtechapi/viewmodels/responses"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

func DeviceRequestToDevice(device *request.Device) *models.Device {

	objID, _ := primitive.ObjectIDFromHex(device.Brand)
	sarValue := float64(0)
	if device.SarValue != nil {
		sarValue = *device.SarValue
	}
	return &models.Device{
		Type:                   device.Type,
		Brand:                  objID,
		CommercialModel:        device.CommercialModel,
		TechnicalModel:         device.TechnicalModel,
		DisplayType:            device.DisplayType,
		DisplaySize:            device.DisplaySize,
		DisplayResolution:      device.DisplayResolution,
		PlatformOs:             device.PlatformOs,
		PlatformVersion:        device.PlatformVersion,
		PlatformChipsetBrand:   device.PlatformChipsetBrand,
		PlatformChipsetModel:   device.PlatformChipsetModel,
		PlatformCpu:            device.PlatformCpu,
		MemoryRom:              device.MemoryRom,
		MemoryRam:              device.MemoryRam,
		MemoryExtended:         device.MemoryExtended,
		MemoryCpu:              device.MemoryCpu,
		MemoryType:             device.MemoryType,
		CameraFront:            device.CameraFront,
		CameraBack:             device.CameraBack,
		CommunicationWlan:      device.CommunicationWlan,
		CommunicationGps:       device.CommunicationGps,
		CommunicationNfc:       device.CommunicationNfc,
		CommunicationRadio:     device.CommunicationRadio,
		CommunicationUsb:       device.CommunicationUsb,
		CommunicationBluetooth: device.CommunicationBluetooth,
		BatteryType:            device.BatteryType,
		BatteryCapacity:        device.BatteryCapacity,
		BatteryState:           device.BatteryState,
		SensorFingerprint:      device.SensorFingerprint,
		SensorProximity:        device.SensorProximity,
		SensorAmbientLight:     device.SensorAmbientLight,
		SensorAccelerometer:    device.SensorAccelerometer,
		SensorGyroscope:        device.SensorGyroscope,
		SensorHall:             device.SensorHall,
		BandGsm:                device.BandGsm,
		BandWcdma:              device.BandWcdma,
		BandLte:                device.BandLte,
		Band5g:                 device.Band5g,
		CarrierAgg:             device.CarrierAgg,
		NetworkGsm:             device.NetworkGsm,
		NetworkWcdma:           device.NetworkWcdma,
		NetworkLte:             device.NetworkLte,
		NetworkVolte:           device.NetworkVolte,
		NetworkVowifi:          device.NetworkVowifi,
		NetworkVilte:           device.NetworkVilte,
		Network5g:              device.Network5g,
		NetworkCarrierAgg:      device.NetworkCarrierAgg,
		ImageUrl:               device.ImageUrl,
		SoftwareCode:           device.SoftwareCode,
		HardwareCode:           device.HardwareCode,
		IngCode:                device.IngCode,
		LoggingCode:            device.LoggingCode,
		SimSupported:           device.SimSupported,
		DualSim:                device.DualSim,
		SimType:                device.SimType,
		Esim:                   device.Esim,
		SarValue:               sarValue,
		BatteryInductedCharger: device.BatteryInductedCharger,
	}
}
func DeviceToDeviceResponse(device *models.Device) *responses.DeviceExpanded {

	brand := new(responses.Brand)
	brand.ID = device.Brand
	return &responses.DeviceExpanded{
		ID:                     device.ID,
		Type:                   device.Type,
		Brand:                  *brand,
		CommercialModel:        device.CommercialModel,
		TechnicalModel:         device.TechnicalModel,
		DisplayType:            device.DisplayType,
		DisplaySize:            device.DisplaySize,
		DisplayResolution:      device.DisplayResolution,
		PlatformOs:             device.PlatformOs,
		PlatformVersion:        device.PlatformVersion,
		PlatformChipsetBrand:   device.PlatformChipsetBrand,
		PlatformChipsetModel:   device.PlatformChipsetModel,
		PlatformCpu:            device.PlatformCpu,
		MemoryRom:              device.MemoryRom,
		MemoryRam:              device.MemoryRam,
		MemoryExtended:         device.MemoryExtended,
		MemoryCpu:              device.MemoryCpu,
		MemoryType:             device.MemoryType,
		CameraFront:            device.CameraFront,
		CameraBack:             device.CameraBack,
		CommunicationWlan:      device.CommunicationWlan,
		CommunicationGps:       device.CommunicationGps,
		CommunicationNfc:       device.CommunicationNfc,
		CommunicationRadio:     device.CommunicationRadio,
		CommunicationUsb:       device.CommunicationUsb,
		CommunicationBluetooth: device.CommunicationBluetooth,
		BatteryType:            device.BatteryType,
		BatteryCapacity:        device.BatteryCapacity,
		BatteryState:           device.BatteryState,
		SensorFingerprint:      device.SensorFingerprint,
		SensorProximity:        device.SensorProximity,
		SensorAmbientLight:     device.SensorAmbientLight,
		SensorAccelerometer:    device.SensorAccelerometer,
		SensorGyroscope:        device.SensorGyroscope,
		SensorHall:             device.SensorHall,
		BandGsm:                device.BandGsm,
		BandWcdma:              device.BandWcdma,
		BandLte:                device.BandLte,
		Band5g:                 device.Band5g,
		CarrierAgg:             device.CarrierAgg,
		NetworkGsm:             device.NetworkGsm,
		NetworkWcdma:           device.NetworkWcdma,
		NetworkLte:             device.NetworkLte,
		NetworkVolte:           device.NetworkVolte,
		NetworkVowifi:          device.NetworkVowifi,
		NetworkVilte:           device.NetworkVilte,
		Network5g:              device.Network5g,
		NetworkCarrierAgg:      device.NetworkCarrierAgg,
		ImageUrl:               device.ImageUrl,
		SoftwareCode:           device.SoftwareCode,
		HardwareCode:           device.HardwareCode,
		IngCode:                device.IngCode,
		LoggingCode:            device.LoggingCode,
		SimSupported:           device.SimSupported,
		DualSim:                device.DualSim,
		SimType:                device.SimType,
		Esim:                   device.Esim,
		SarValue:               device.SarValue,
		BatteryInductedCharger: device.BatteryInductedCharger,
	}
}
