root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "./tmp/main.exe"
  delay = 1000
  exclude_dir = ["tmp", "docs", "utils/htmlMessageTemplate"]
  include_ext = ["go"]
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500

[log]
  main_only = true
  time = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
